// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvjyiPueCRcmcax9Z-gYbBy7cHNe2Fr_o',
    appId: '1:1060272951544:web:253acd866e81a7d6c8ab0d',
    messagingSenderId: '1060272951544',
    projectId: 'streetfoodmarket-5f781',
    authDomain: 'streetfoodmarket-5f781.firebaseapp.com',
    storageBucket: 'streetfoodmarket-5f781.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9IUAKi0J9rtbNizwW_SY9IORhcec9H5U',
    appId: '1:1060272951544:android:d6ba3e0dd1ef1cfdc8ab0d',
    messagingSenderId: '1060272951544',
    projectId: 'streetfoodmarket-5f781',
    storageBucket: 'streetfoodmarket-5f781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmXs2ki3U5efxQJX9UOyv8DS_f05tgBg8',
    appId: '1:1060272951544:ios:fae2f54e2e4f5479c8ab0d',
    messagingSenderId: '1060272951544',
    projectId: 'streetfoodmarket-5f781',
    storageBucket: 'streetfoodmarket-5f781.firebasestorage.app',
    iosBundleId: 'com.example.streetFoodMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmXs2ki3U5efxQJX9UOyv8DS_f05tgBg8',
    appId: '1:1060272951544:ios:fae2f54e2e4f5479c8ab0d',
    messagingSenderId: '1060272951544',
    projectId: 'streetfoodmarket-5f781',
    storageBucket: 'streetfoodmarket-5f781.firebasestorage.app',
    iosBundleId: 'com.example.streetFoodMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvjyiPueCRcmcax9Z-gYbBy7cHNe2Fr_o',
    appId: '1:1060272951544:web:8120fa8b34ef2906c8ab0d',
    messagingSenderId: '1060272951544',
    projectId: 'streetfoodmarket-5f781',
    authDomain: 'streetfoodmarket-5f781.firebaseapp.com',
    storageBucket: 'streetfoodmarket-5f781.firebasestorage.app',
  );
}
